'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {money} from '@/lib/config/defaults'
import {useCart} from '@/components/cart/CartProvider'
type Order={reference:string;fulfillmentStatus:string;paymentStatus:string;method:string;paymentMethod:string;subtotalCents:number;feeCents:number;totalCents:number;createdAt:string;items:{name:string;quantity:number;lineCents:number;choices:{label:string}[];notes?:string}[];events:{status:string;created_at:string}[]}
const label:Record<string,string>={novo:'Recebido',confirmado:'Confirmado',em_preparo:'Em preparo',pronto_para_retirada:'Pronto para retirada',saiu_para_entrega:'Saiu para entrega',concluido:'Concluído',cancelado:'Cancelado',pending:'Pendente',approved:'Aprovado',rejected:'Recusado',cancelled:'Cancelado',refunded:'Estornado'}
export function Tracking({reference,initialToken}:{reference:string;initialToken:string}){const [token,setToken]=useState(initialToken),[order,setOrder]=useState<Order|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[reorderMessage,setReorderMessage]=useState(''),[payBusy,setPayBusy]=useState(false);const {add}=useCart()
 useEffect(()=>{const handle=requestAnimationFrame(()=>{if(!token)setToken(localStorage.getItem(`brutus-order-${reference}`)||'')});return()=>cancelAnimationFrame(handle)},[token,reference])
 useEffect(()=>{if(!token){const handle=requestAnimationFrame(()=>setLoading(false));return()=>cancelAnimationFrame(handle)}let active=true;async function refresh(){try{const res=await fetch(`/api/orders/${encodeURIComponent(reference)}?token=${token}`,{cache:'no-store'});if(!res.ok)throw Error('Link inválido, expirado ou pedido indisponível.');const result=await res.json();if(active){setOrder(result);setError('')}}catch(e){if(active)setError((e as Error).message)}finally{if(active)setLoading(false)}}refresh();const timer=setInterval(refresh,15000);return()=>{active=false;clearInterval(timer)}},[reference,token]);
 if(loading)return <div className="track-card">Carregando pedido…</div>
 if(!token)return <div className="track-card">Este pedido exige seu link privado de acompanhamento. <Link href="/meus-pedidos">Ver pedidos salvos neste navegador</Link></div>
 if(error&&!order)return <div className="track-card" role="alert">{error}</div>
 if(!order)return null
 async function reopenPayment(){setPayBusy(true);try{const response=await fetch('/api/payments/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reference,token})});const data=await response.json();if(!response.ok)throw Error(data.error||'Pagamento indisponível');location.assign(data.url)}catch(e){setError((e as Error).message);setPayBusy(false)}}
 async function reorder(){try{const response=await fetch(`/api/orders/${encodeURIComponent(reference)}/reorder?token=${token}`);const result=await response.json();if(!response.ok)throw Error(result.error);result.lines.forEach((line:import('@/types').CartLine)=>add(line));setReorderMessage(result.lines.length?`${result.lines.length} item(ns) adicionado(s) com preço atual; ${result.skipped} indisponível(is). Confira o carrinho.`:'Nenhum item continua disponível para repetir.')}catch(e){setReorderMessage((e as Error).message)}}
 return <div className="track-card">{error&&<p role="alert" className="field-error">{error} Os dados abaixo podem estar desatualizados.</p>}<div className="track-top"><div><span className="kicker">{order.reference}</span><h2>{label[order.fulfillmentStatus]||order.fulfillmentStatus}</h2></div><span className="status-pill">Pagamento: {label[order.paymentStatus]||order.paymentStatus}</span></div><p>Modalidade: {order.method==='pickup'?'Retirada':'Entrega'} · Atualização automática a cada 15 segundos.</p><div className="track-events">{order.events.map((e,i)=><div key={i}><span className="track-dot"/><strong>{label[e.status]||e.status}</strong><time>{new Date(e.created_at).toLocaleString('pt-BR')}</time></div>)}</div><h3>Itens</h3>{order.items.map((l,i)=><div className="checkout-row" key={i}><span>{l.quantity}× {l.name}<small>{l.choices.map(c=>c.label).join(' · ')}</small>{l.notes&&<small>Obs.: {l.notes}</small>}</span><strong>{money(l.lineCents)}</strong></div>)}<div className="checkout-row"><span>Taxa</span><strong>{money(order.feeCents)}</strong></div><div className="checkout-total"><span>Total</span><strong>{money(order.totalCents)}</strong></div>{reorderMessage&&<p role="status">{reorderMessage}</p>}<div className="button-row">{order.paymentMethod==='online'&&order.paymentStatus==='pending'&&order.fulfillmentStatus!=='cancelado'&&<button disabled={payBusy} className="button button-dark" onClick={reopenPayment}>{payBusy?'Abrindo…':'Abrir pagamento pendente ↗'}</button>}<button className="button button-accent" onClick={reorder}>Pedir novamente ↗</button><Link className="button button-outline" href="/cardapio">Voltar ao cardápio ↗</Link></div></div>}
