'use client'
import {createContext,useContext,useEffect,useRef,useState} from 'react'
import Link from 'next/link'
import {X,Trash2} from 'lucide-react'
import {ProductPhoto} from '@/components/menu/ProductPhoto'
import {money} from '@/lib/config/defaults'
import type {CartLine} from '@/types'
type CartState={lines:CartLine[];add:(line:CartLine)=>void;replace:(oldKey:string,line:CartLine)=>void;remove:(key:string)=>void;quantity:(key:string,n:number)=>void;clear:()=>void;drawer:boolean;setDrawer:(open:boolean)=>void}
const Context=createContext<CartState|null>(null)
export function useCart(){const value=useContext(Context);if(!value)throw Error('CartProvider ausente');return value}
export function CartProvider({children,preview=false}:{children:React.ReactNode;preview?:boolean}){
 const [lines,setLines]=useState<CartLine[]>([]),[drawer,setDrawer]=useState(false),[ready,setReady]=useState(false),dialog=useRef<HTMLElement>(null)
 useEffect(()=>{const handle=requestAnimationFrame(()=>{try{const v=JSON.parse(localStorage.getItem('brutus-cart-v1')||'[]');if(Array.isArray(v))setLines(v.filter(x=>x?.productId&&x.quantity>0))}catch{}setReady(true)});return()=>cancelAnimationFrame(handle)},[])
 useEffect(()=>{if(ready)localStorage.setItem('brutus-cart-v1',JSON.stringify(lines))},[lines,ready])
 useEffect(()=>{if(!drawer)return;const old=document.body.style.overflow,previous=document.activeElement as HTMLElement|null;document.body.style.overflow='hidden';function key(e:KeyboardEvent){if(e.key==='Escape')setDrawer(false);if(e.key==='Tab'){const nodes=dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled)'),first=nodes?.[0],last=nodes?.[nodes.length-1];if(!first)return;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}addEventListener('keydown',key);return()=>{document.body.style.overflow=old;removeEventListener('keydown',key);previous?.focus()}},[drawer])
 const add=(line:CartLine)=>{setLines(prev=>{const found=prev.find(x=>x.key===line.key);return found?prev.map(x=>x.key===line.key?{...x,quantity:Math.min(20,x.quantity+line.quantity)}:x):[...prev,line]});setDrawer(true)}
 const replace=(oldKey:string,line:CartLine)=>{setLines(prev=>{const other=prev.find(x=>x.key===line.key&&x.key!==oldKey);return other?prev.filter(x=>x.key!==oldKey).map(x=>x.key===line.key?{...x,quantity:Math.min(20,x.quantity+line.quantity)}:x):prev.map(x=>x.key===oldKey?line:x)});setDrawer(true)}
 const quantity=(key:string,n:number)=>setLines(prev=>prev.map(x=>x.key===key?{...x,quantity:Math.min(20,Math.max(1,n))}:x))
 const remove=(key:string)=>setLines(prev=>prev.filter(x=>x.key!==key))
 return <Context.Provider value={{lines,add,replace,quantity,remove,clear:()=>setLines([]),drawer,setDrawer}}>{children}{drawer&&<div className="drawer-backdrop" onMouseDown={()=>setDrawer(false)}><aside ref={dialog} className="cart-drawer" role="dialog" aria-modal="true" aria-label="Seu carrinho" onMouseDown={e=>e.stopPropagation()}><div className="drawer-top"><div><span className="kicker">SEU PEDIDO</span><h2>Carrinho <small>({lines.reduce((n,l)=>n+l.quantity,0)})</small></h2></div><button autoFocus onClick={()=>setDrawer(false)} aria-label="Fechar carrinho" className="round-close"><X/></button></div><div className="drawer-lines">{lines.length===0?<p className="empty-cart">Seu carrinho está vazio.<br/>O primeiro passo é olhar o cardápio.</p>:lines.map(line=><div className="cart-line" key={line.key}><div className="cart-product-photo"><ProductPhoto productId={line.productId} url={line.imageUrl} name={line.name}/></div><div className="cart-line-main"><h3>{line.name}</h3><p>{line.choiceLabels.join(' · ')||'Sem personalização'}</p>{line.notes&&<p className="cart-line-note">Obs.: {line.notes}</p>}<strong>{money(line.unitPriceCents*line.quantity)}</strong><div className="quantity-controls"><button aria-label={`Diminuir ${line.name}`} onClick={()=>line.quantity===1?remove(line.key):quantity(line.key,line.quantity-1)}>−</button><span>{line.quantity}</span><button aria-label={`Aumentar ${line.name}`} onClick={()=>quantity(line.key,line.quantity+1)}>+</button></div><Link className="cart-edit" href={`/cardapio?editar=${encodeURIComponent(line.key)}`} onClick={()=>setDrawer(false)}>Editar escolhas</Link></div><button onClick={()=>remove(line.key)} aria-label={`Remover ${line.name}`} className="remove"><Trash2 size={17}/></button></div>)}</div><div className="drawer-bottom"><div><span>Subtotal estimado</span><strong>{money(lines.reduce((n,l)=>n+l.unitPriceCents*l.quantity,0))}</strong></div><p>{preview?'Revise os dados e envie o pedido pronto para o WhatsApp da Brutus.':'A taxa de entrega, se houver, aparece antes de confirmar o pedido.'}</p>{lines.length?<Link className="button button-accent" href="/checkout" onClick={()=>setDrawer(false)}>{preview?'Finalizar no WhatsApp':'Continuar pedido'} ↗</Link>:<Link className="button button-dark" href="/cardapio" onClick={()=>setDrawer(false)}>Ver cardápio ↗</Link>}</div></aside></div>}</Context.Provider>
}
