'use client'
import {useState,useEffect,useRef,useCallback} from 'react'
import {X,Plus} from 'lucide-react'
import {ProductPhoto} from './ProductPhoto'
import type {Product,CartLine} from '@/types'
import {money} from '@/lib/config/defaults'
import {useCart} from '@/components/cart/CartProvider'
export function ProductGrid({products,emptyText,open=true}:{products:Product[];emptyText:string;open?:boolean}){const [selected,setSelected]=useState<{product:Product;initial?:CartLine}|null>(null),{lines}=useCart(),close=useCallback(()=>setSelected(null),[setSelected])
 useEffect(()=>{if(window.location.pathname!=='/cardapio')return;const key=new URLSearchParams(window.location.search).get('editar');const line=lines.find(l=>l.key===key);const product=products.find(p=>p.id===line?.productId);if(line&&product){const frame=requestAnimationFrame(()=>{setSelected({product,initial:line});history.replaceState(history.state,'','/cardapio')});return()=>cancelAnimationFrame(frame)}},[lines,products])
 return <>{products.length===0?<div className="empty-state"><span className="empty-glyph">B.</span><h3>Em breve por aqui.</h3><p>{emptyText}</p></div>:<div className="product-grid">{products.map((p,i)=><article className="product-card" key={p.id} id={`produto-${p.slug}`}><button className="product-photo" onClick={()=>setSelected({product:p})} aria-label={`Ver ${p.name}`}><ProductPhoto productId={p.id} url={p.image_url} name={p.name}/><span className="product-number">{String(i+1).padStart(2,'0')}</span></button><div className="product-info"><span className="product-caption">{p.available?'NO CARDÁPIO':'INDISPONÍVEL'}</span><h3>{p.name}</h3><p>{p.description}</p><div className="product-bottom"><strong>{money(p.price_cents)}</strong><button className="product-add" disabled={!p.available||!open} onClick={()=>setSelected({product:p})} aria-label={`Personalizar ${p.name}`}><Plus size={19}/></button></div></div></article>)}</div>}{selected&&<Customizer key={`${selected.product.id}:${selected.initial?.key||'new'}`} product={selected.product} initial={selected.initial} onClose={close} open={open}/>}</>}
function Customizer({product,initial,onClose,open}:{product:Product;initial?:CartLine;onClose:()=>void;open:boolean}){
 const [selected,setSelected]=useState<Record<string,string[]>>(()=>Object.fromEntries(product.groups.map(g=>[g.id,g.choices.filter(c=>initial?.choices.includes(c.id)).map(c=>c.id)]))),[quantity,setQuantity]=useState(initial?.quantity||1),[notes,setNotes]=useState(initial?.notes||''),[error,setError]=useState('');const {add,replace}=useCart();const close=useRef<HTMLButtonElement>(null)
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;close.current?.focus();function handle(e:KeyboardEvent){if(e.key==='Escape')onClose();if(e.key==='Tab'){const focusable=document.querySelectorAll<HTMLElement>('.customizer button:not(:disabled),.customizer input:not(:disabled),.customizer textarea:not(:disabled),.customizer select:not(:disabled)');const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}addEventListener('keydown',handle);return()=>{removeEventListener('keydown',handle);previous?.focus()}},[onClose])
 const selectedChoices=product.groups.flatMap(g=>g.choices.filter(c=>(selected[g.id]||[]).includes(c.id)))
 const unit=product.price_cents+selectedChoices.reduce((n,c)=>n+c.price_cents,0)
 const toggle=(group:Product['groups'][number],id:string)=>{setError('');setSelected(prev=>{const before=prev[group.id]||[];return {...prev,[group.id]:before.includes(id)?before.filter(x=>x!==id):group.max_select===1?[id]:before.length<group.max_select?[...before,id]:before}})}
 function submit(){for(const group of product.groups){const count=(selected[group.id]||[]).length;if(count<group.min_select||count>group.max_select){setError(`Confira as opções de ${group.title.toLowerCase()}.`);return}}const ids=selectedChoices.map(c=>c.id).sort(),cleanNotes=notes.trim();const line={key:`${product.id}:${ids.join(',')}:${encodeURIComponent(cleanNotes.toLocaleLowerCase('pt-BR'))}`,productId:product.id,quantity,choices:ids,name:product.name,imageUrl:product.image_url,unitPriceCents:unit,choiceLabels:selectedChoices.map(c=>c.label),notes:cleanNotes};if(initial)replace(initial.key,line);else add(line);onClose()}
 return <div className="modal-backdrop" onMouseDown={onClose}><div className="customizer" role="dialog" aria-modal="true" aria-label={`Personalizar ${product.name}`} onMouseDown={e=>e.stopPropagation()}><button ref={close} className="round-close modal-close" onClick={onClose} aria-label="Fechar"><X/></button><div className="customizer-image"><ProductPhoto productId={product.id} url={product.image_url} name={product.name}/></div><div className="customizer-body"><span className="kicker">FAÇA DO SEU JEITO</span><h2>{product.name}</h2><p>{product.description}</p>{product.groups.map(g=><fieldset key={g.id} className="option-group"><legend>{g.title} <small>{g.min_select?`Escolha ${g.min_select} a ${g.max_select}`:`Até ${g.max_select} opção(ões)`}</small></legend>{g.choices.map(c=><label key={c.id} className="choice"><input type={g.max_select===1?'radio':'checkbox'} name={g.id} checked={(selected[g.id]||[]).includes(c.id)} onChange={()=>toggle(g,c.id)}/><span>{c.label}</span><strong>{c.price_cents?`+ ${money(c.price_cents)}`:'Incluso'}</strong></label>)}</fieldset>)}<label className="input-field item-notes">Observações deste item<textarea value={notes} onChange={event=>setNotes(event.target.value)} maxLength={180} placeholder="Ex.: remover cebola"/></label><div className="customizer-qty"><span>Quantidade</span><div className="quantity-controls"><button onClick={()=>setQuantity(Math.max(1,quantity-1))} aria-label="Diminuir quantidade">−</button>{quantity}<button onClick={()=>setQuantity(Math.min(product.max_per_order||20,quantity+1))} aria-label="Aumentar quantidade">+</button></div></div>{error&&<p role="alert" className="field-error">{error}</p>}<button className="button button-accent modal-submit" disabled={!open||!product.available} onClick={submit}>{!open?'Pedidos fechados':!product.available?'Indisponível':`${initial?'Atualizar carrinho':'Adicionar'} · ${money(unit*quantity)}`} <span aria-hidden>↗</span></button></div></div></div>
}
