import {requireStaff} from '@/lib/auth/staff'
import {db} from '@/lib/db/pool'
import {AdminShell} from '@/components/admin/AdminShell'
import {EntityEditor} from '@/components/admin/EntityEditor'
import {SettingsPanel} from '@/components/admin/SettingsPanel'
export const dynamic='force-dynamic'
export default async function Operations(){const staff=await requireStaff(true);const [hours,exceptions,modes,areas,settings]=await Promise.all(['opening_hours','opening_exceptions','service_modes','delivery_areas','site_settings'].map(t=>db().query(`select * from ${t} order by ${t==='opening_hours'?'day_of_week':t==='opening_exceptions'?'day':t==='service_modes'?'mode':t==='site_settings'?'key':'label'}`)));return <AdminShell staff={staff} title="Operação"><p className="admin-intro">Defina horário em Matão, modalidades e faixas de CEP antes de abrir os pedidos. Uma faixa de CEP deve refletir apenas a área confirmada pela empresa.</p>
 <SettingsPanel rows={settings.rows.filter(r=>['orders_open','pickup_enabled','delivery_enabled','online_payment_enabled','offline_payment_enabled','address','notice'].includes(r.key))}/>
 <EntityEditor title="Modalidades" entity="service_modes" rows={modes.rows} initial={{mode:'pickup',enabled:false,minimum_cents:0}} fields={[{key:'mode',label:'Modalidade',type:'select',options:[{value:'pickup',label:'Retirada'},{value:'delivery',label:'Entrega'}]},{key:'enabled',label:'Ativa',type:'checkbox'},{key:'minimum_cents',label:'Valor mínimo (R$)',type:'money'}]}/>
 <EntityEditor title="Horários da semana" entity="opening_hours" rows={hours.rows} initial={{day_of_week:0,opens_at:'18:00',closes_at:'23:00',enabled:false}} fields={[{key:'day_of_week',label:'Dia da semana (0 = domingo, 6 = sábado)',type:'number'},{key:'opens_at',label:'Abre às',type:'time'},{key:'closes_at',label:'Fecha às',type:'time'},{key:'enabled',label:'Aberto neste dia',type:'checkbox'}]}/>
 <EntityEditor title="Exceções de horário" entity="opening_exceptions" rows={exceptions.rows} initial={{day:new Date().toISOString().slice(0,10),open:false,opens_at:null,closes_at:null,reason:null}} fields={[{key:'day',label:'Data',type:'date'},{key:'open',label:'Aberto nesta data',type:'checkbox'},{key:'opens_at',label:'Abre às (se aberto)',type:'time'},{key:'closes_at',label:'Fecha às (se aberto)',type:'time'},{key:'reason',label:'Aviso interno'}]}/>
 <EntityEditor title="Áreas e taxas de entrega" entity="delivery_areas" rows={areas.rows} initial={{label:'',zip_start:0,zip_end:0,fee_cents:0,active:false}} fields={[{key:'label',label:'Identificação da área'},{key:'zip_start',label:'CEP inicial (8 dígitos, sem traço)',type:'number'},{key:'zip_end',label:'CEP final (8 dígitos, sem traço)',type:'number'},{key:'fee_cents',label:'Taxa (R$)',type:'money'},{key:'active',label:'Ativa',type:'checkbox'}]}/>
 </AdminShell>}
