import {requireStaff} from '@/lib/auth/staff'
import {db} from '@/lib/db/pool'
import {AdminShell} from '@/components/admin/AdminShell'
import {EntityEditor} from '@/components/admin/EntityEditor'
export const dynamic='force-dynamic'
export default async function CatalogAdmin(){const staff=await requireStaff(true);const [c,p,g,ch,links,images]=await Promise.all(['categories','products','option_groups','option_choices','product_option_groups','product_images'].map(t=>db().query(`select * from ${t} order by ${'sort_order'} limit 200`)));const categories=c.rows.map(r=>({value:r.id,label:r.name})),products=p.rows.map(r=>({value:r.id,label:r.name})),groups=g.rows.map(r=>({value:r.id,label:r.title}));return <AdminShell staff={staff} title="Cardápio"><p className="admin-intro">Comece por categorias, depois cadastre produtos e opções. A publicação exige “Aprovado” em cada item.</p>
 <EntityEditor title="Categorias" entity="categories" rows={c.rows} initial={{name:'',slug:'',description:'',sort_order:0,active:true,approved:false}} fields={[{key:'name',label:'Nome'},{key:'slug',label:'Endereço curto (slug)'},{key:'description',label:'Descrição',type:'textarea'},{key:'sort_order',label:'Ordem',type:'number'},{key:'active',label:'Ativa',type:'checkbox'},{key:'approved',label:'Aprovada para publicar',type:'checkbox'}]}/>
 <EntityEditor title="Produtos" entity="products" rows={p.rows} initial={{category_id:categories[0]?.value||'',name:'',slug:'',description:'',price_cents:0,featured:false,active:true,approved:false,available:true,show_when_unavailable:true,sort_order:0,max_per_order:null}} fields={[{key:'category_id',label:'Categoria',type:'select',options:categories},{key:'name',label:'Nome'},{key:'slug',label:'Slug'},{key:'description',label:'Descrição',type:'textarea'},{key:'price_cents',label:'Preço base (R$)',type:'money'},{key:'max_per_order',label:'Limite por pedido (opcional)',type:'number'},{key:'sort_order',label:'Ordem',type:'number'},{key:'featured',label:'Destaque na home',type:'checkbox'},{key:'active',label:'Ativo',type:'checkbox'},{key:'approved',label:'Aprovado pela Brutus',type:'checkbox'},{key:'available',label:'Disponível',type:'checkbox'},{key:'show_when_unavailable',label:'Exibir mesmo indisponível',type:'checkbox'}]}/>
 <EntityEditor title="Fotos de produtos" entity="product_images" rows={images.rows} initial={{product_id:products[0]?.value||'',url:'',alt:'',approved:false,sort_order:0}} fields={[{key:'product_id',label:'Produto',type:'select',options:products},{key:'url',label:'Imagem / enviar arquivo',type:'image'},{key:'alt',label:'Descrição acessível'},{key:'sort_order',label:'Ordem',type:'number'},{key:'approved',label:'Aprovada para publicar',type:'checkbox'}]}/>
 <EntityEditor title="Grupos de opções" entity="option_groups" rows={g.rows} initial={{title:'',min_select:0,max_select:1,active:true,sort_order:0}} fields={[{key:'title',label:'Nome (ex.: molho)'},{key:'min_select',label:'Mínimo de escolhas',type:'number'},{key:'max_select',label:'Máximo de escolhas',type:'number'},{key:'sort_order',label:'Ordem',type:'number'},{key:'active',label:'Ativo',type:'checkbox'}]}/>
 <EntityEditor title="Opções e adicionais" entity="option_choices" rows={ch.rows} initial={{group_id:groups[0]?.value||'',label:'',price_cents:0,active:true,sort_order:0}} fields={[{key:'group_id',label:'Grupo',type:'select',options:groups},{key:'label',label:'Nome'},{key:'price_cents',label:'Valor adicional (R$)',type:'money'},{key:'sort_order',label:'Ordem',type:'number'},{key:'active',label:'Ativa',type:'checkbox'}]}/>
 <EntityEditor title="Vincular grupo a produto" entity="product_option_groups" rows={links.rows} initial={{product_id:products[0]?.value||'',group_id:groups[0]?.value||'',sort_order:0}} fields={[{key:'product_id',label:'Produto',type:'select',options:products},{key:'group_id',label:'Grupo de opções',type:'select',options:groups},{key:'sort_order',label:'Ordem',type:'number'}]}/>
 </AdminShell>}
