'use client'
import {useEffect,useRef,useState} from 'react'
import Link from 'next/link'
import {money} from '@/lib/config/defaults'
type Order={id:string;reference:string;customer_name:string;customer_phone:string;fulfillment_method:string;fulfillment_status:string;payment_method:string;payment_status:string;total_cents:number;created_at:string;delivery_address:Record<string,string>|null;notes:string|null;items:{name:string;quantity:number;lineCents:number;choices:{label:string}[];notes?:string}[]}
const possible:Record<string,string[]>= {novo:['confirmado','cancelado'],confirmado:['em_preparo','cancelado'],em_preparo:['pronto_para_retirada','saiu_para_entrega','cancelado'],pronto_para_retirada:['concluido'],saiu_para_entrega:['concluido']}
const labels:Record<string,string>={novo:'Novo',confirmado:'Confirmado',em_preparo:'Em preparo',pronto_para_retirada:'Pronto para retirada',saiu_para_entrega:'Saiu para entrega',concluido:'Concluído',cancelado:'Cancelado'}
export function OrdersPanel(){const [orders,setOrders]=useState<Order[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[filter,setFilter]=useState('ativos'),[term,setTerm]=useState(''),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),seen=useRef<Set<string>|null>(null)
 useEffect(()=>{let active=true;async function fetchOrders(){try{const res=await fetch('/api/admin/orders',{cache:'no-store'});if(!res.ok)throw Error('Não foi possível atualizar pedidos');const data=await res.json();if(active){if(seen.current){const added=data.filter((o:Order)=>!seen.current?.has(o.id)).length;if(added)setNotice(`${added} novo(s) pedido(s) recebido(s).`)}seen.current=new Set(data.map((o:Order)=>o.id));setOrders(data);setError('')}}catch(e){if(active)setError((e as Error).message)}finally{if(active)setLoading(false)}}fetchOrders();const interval=setInterval(fetchOrders,12000);return()=>{active=false;clearInterval(interval)}},[busy])
 async function act(order:Order,action:'status'|'paid',status?:string){let note='';if(status==='cancelado'){const reason=prompt(`Motivo do cancelamento de ${order.reference} (cancelar não estorna pagamento automaticamente):`);if(!reason)return;note=reason}if(!confirm(action==='paid'?`Confirmar recebimento do pagamento de ${order.reference}?`:`Mudar ${order.reference} para ${labels[status||'']}?`))return;setBusy(order.id);setError('');try{const res=await fetch('/api/admin/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:order.id,action,status,note})});const data=await res.json();if(!res.ok)throw Error(data.error);setOrders(v=>v.map(o=>o.id===order.id?{...o,fulfillment_status:status||o.fulfillment_status,payment_status:action==='paid'?'approved':o.payment_status}:o))}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 const list=orders.filter(o=>(filter==='todos'||filter==='ativos'&&!['concluido','cancelado'].includes(o.fulfillment_status)||o.fulfillment_status===filter)&&`${o.reference} ${o.customer_name}`.toLowerCase().includes(term.toLowerCase()))
 return <div className="admin-section"><p role="status" aria-live="polite">{notice}</p><div className="admin-toolbar"><input aria-label="Buscar referência ou cliente" placeholder="Buscar referência ou nome" value={term} onChange={e=>setTerm(e.target.value)}/><select aria-label="Filtrar status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ativos">Ativos</option><option value="todos">Todos</option>{Object.keys(labels).map(k=><option value={k} key={k}>{labels[k]}</option>)}</select></div>{error&&<div role="alert" className="admin-alert">{error}</div>}{loading?<p>Carregando pedidos…</p>:list.length===0?<p className="admin-empty">Nenhum pedido corresponde ao filtro.</p>:<div className="admin-order-list">{list.map(o=><article key={o.id} className="admin-order"><div className="admin-order-head"><div><span className="kicker">{o.reference}</span><h2>{o.customer_name}</h2><small>{new Date(o.created_at).toLocaleString('pt-BR')} · {o.customer_phone}</small></div><div><strong>{money(o.total_cents)}</strong><small>{labels[o.fulfillment_status]} · {o.payment_status==='approved'?'Pago':'Pagamento '+o.payment_status}</small></div></div><p>{o.fulfillment_method==='pickup'?'Retirada':'Entrega'}{o.delivery_address?` · ${o.delivery_address.street}, ${o.delivery_address.number}, ${o.delivery_address.district} — ${o.delivery_address.postalCode}`:''}{o.delivery_address?.reference?` · Referência: ${o.delivery_address.reference}`:''}{o.notes?` · Observações: ${o.notes}`:''}</p><div className="admin-order-items">{o.items.map((l,i)=><div key={i}>{l.quantity}× {l.name} {l.choices.map(c=>c.label).join(', ')} · {money(l.lineCents)}{l.notes&&<small> · Obs.: {l.notes}</small>}</div>)}</div><div className="admin-actions"><Link href={`/admin/pedidos/${o.id}`}>Ficha / impressão</Link>{o.payment_method==='offline'&&o.payment_status==='pending'&&<button disabled={busy===o.id} onClick={()=>act(o,'paid')}>Registrar recebimento</button>}{(possible[o.fulfillment_status]||[]).filter(s=>s==='cancelado'||s==='pronto_para_retirada'&&o.fulfillment_method==='pickup'||s==='saiu_para_entrega'&&o.fulfillment_method==='delivery'||!['pronto_para_retirada','saiu_para_entrega'].includes(s)).map(s=><button key={s} disabled={busy===o.id||o.payment_method==='online'&&o.payment_status!=='approved'&&s!=='cancelado'} onClick={()=>act(o,'status',s)}>{labels[s]}</button>)}</div></article>)}</div>}</div>}
