'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
type Setting={key:string;value:string|boolean|null}
const labels:Record<string,string>={headline:'Frase principal',intro:'Texto de apresentação',address:'Endereço confirmado',phone:'Telefone confirmado',instagram:'Perfil do Instagram',logo_url:'Logotipo oficial (URL)',hero_image:'Fotografia oficial da capa (URL)',notice:'Aviso público',orders_open:'Receber pedidos agora',pickup_enabled:'Oferecer retirada',delivery_enabled:'Oferecer entrega',online_payment_enabled:'Aceitar pagamento online',offline_payment_enabled:'Aceitar pagamento no atendimento'}
export function SettingsPanel({rows}:{rows:Setting[]}){const router=useRouter(),[saving,setSaving]=useState(''),[error,setError]=useState(''),[done,setDone]=useState(''),[values,setValues]=useState<Record<string,string|boolean|null>>(Object.fromEntries(rows.map(r=>[r.key,r.value])))
 async function upload(key:string,file:File){if(!confirm('A Brutus autorizou a publicação desta imagem?'))return;setSaving(key);setError('');try{const form=new FormData();form.set('file',file);form.set('approved','true');const response=await fetch('/api/admin/media',{method:'POST',body:form}),data=await response.json();if(!response.ok)throw Error(data.error);setValues(v=>({...v,[key]:data.url}));setDone('Imagem enviada. Clique em Salvar para aplicá-la ao site.')}catch(e){setError((e as Error).message)}finally{setSaving('')}}
 async function save(key:string){setSaving(key);setError('');setDone('');try{const res=await fetch('/api/admin/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({entity:'site_settings',record:{key,value:values[key]||typeof values[key]==='boolean'?values[key]:null}})}),result=await res.json();if(!res.ok)throw Error(result.error);setDone(`Salvo: ${labels[key]}`);router.refresh()}catch(e){setError((e as Error).message)}finally{setSaving('')}}
 return <section className="admin-editor"><div className="admin-editor-head"><h2>Configurações</h2></div><div className="settings-grid">{rows.map(r=><div key={r.key} className="setting"><label>{labels[r.key]||r.key}{typeof r.value==='boolean'?<input type="checkbox" checked={Boolean(values[r.key])} onChange={e=>setValues(v=>({...v,[r.key]:e.target.checked}))}/>:<input value={String(values[r.key]??'')} onChange={e=>setValues(v=>({...v,[r.key]:e.target.value}))} placeholder="Ainda não confirmado"/>}</label>{['hero_image','logo_url'].includes(r.key)&&<><label className="input-field">Enviar imagem autorizada<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" disabled={!!saving} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(r.key,file)}}/></label>{values[r.key]&&<img className="admin-image-preview" src={String(values[r.key])} alt={`Prévia: ${labels[r.key]}`}/>}</>}<button disabled={!!saving} onClick={()=>save(r.key)}>{saving===r.key?'Salvando…':'Salvar'}</button></div>)}{error&&<p role="alert" className="field-error">{error}</p>}{done&&<p role="status">{done}</p>}</div></section>
}
