'use client'
import Link from 'next/link'
import {useState} from 'react'
import {useCart} from '@/components/cart/CartProvider'
import {money} from '@/lib/config/defaults'
import {buildWhatsAppOrderMessage,whatsappUrl} from '@/lib/whatsapp'
export function CartPreview(){
 const {lines,setDrawer}=useCart()
 const [customerName,setCustomerName]=useState(''),[fulfillment,setFulfillment]=useState<'pickup'|'delivery'>('pickup'),[address,setAddress]=useState(''),[reference,setReference]=useState(''),[payment,setPayment]=useState('Pix'),[notes,setNotes]=useState(''),[error,setError]=useState('')
 function send(){
  if(customerName.trim().length<2){setError('Informe seu nome para enviar o pedido.');return}
  if(fulfillment==='delivery'&&address.trim().length<8){setError('Informe o endereço completo para entrega.');return}
  setError('')
  const message=buildWhatsAppOrderMessage(lines,{customerName,fulfillment,address,reference,payment,notes})
  window.location.href=whatsappUrl(message)
 }
 return <section className="checkout-panel cart-preview"><span className="kicker">FINALIZAR PELO WHATSAPP</span><h2>Seu pedido.</h2><p>Confira os itens e envie a mensagem pronta para a Brutus. O pedido e o valor final serão confirmados no WhatsApp.</p>{lines.map(l=><div className="checkout-row" key={l.key}><span>{l.quantity}× {l.name}<small>{l.choiceLabels.join(' · ')}</small>{l.notes&&<small>Obs.: {l.notes}</small>}</span><strong>{money(l.quantity*l.unitPriceCents)}</strong></div>)}{lines.length>0&&<><div className="checkout-total"><span>Subtotal estimado</span><strong>{money(lines.reduce((n,l)=>n+l.quantity*l.unitPriceCents,0))}</strong></div><div className="whatsapp-order-fields"><label className="input-field">Seu nome<input value={customerName} onChange={event=>setCustomerName(event.target.value)} maxLength={120} autoComplete="name" placeholder="Como a Brutus pode identificar você?"/></label><fieldset className="whatsapp-options"><legend>Como deseja receber?</legend><label className="choice large-choice"><input type="radio" name="fulfillment" checked={fulfillment==='pickup'} onChange={()=>setFulfillment('pickup')}/>Retirada no local</label><label className="choice large-choice"><input type="radio" name="fulfillment" checked={fulfillment==='delivery'} onChange={()=>setFulfillment('delivery')}/>Entrega</label></fieldset>{fulfillment==='delivery'&&<><label className="input-field">Endereço completo<input value={address} onChange={event=>setAddress(event.target.value)} maxLength={240} autoComplete="street-address" placeholder="Rua, número, bairro e complemento"/></label><label className="input-field">Ponto de referência (opcional)<input value={reference} onChange={event=>setReference(event.target.value)} maxLength={120} placeholder="Ex.: perto da praça"/></label></>}<label className="input-field">Forma de pagamento<select value={payment} onChange={event=>setPayment(event.target.value)}><option>Pix</option><option>Dinheiro</option><option>Cartão no atendimento</option></select></label><label className="input-field">Observações do pedido<textarea value={notes} onChange={event=>setNotes(event.target.value)} maxLength={500} placeholder="Opcional"/></label></div>{error&&<p className="checkout-error" role="alert">{error}</p>}<button type="button" className="button button-accent whatsapp-submit" onClick={send}>Enviar pedido no WhatsApp ↗</button><p className="helper">Nenhum pagamento acontece neste botão. A Brutus confirmará disponibilidade, entrega e valor antes de preparar o pedido.</p></>}<div className="button-row">{lines.length>0&&<button type="button" className="button button-dark" onClick={()=>setDrawer(true)}>Editar carrinho</button>}<Link href="/cardapio" className="button button-outline">Voltar ao cardápio ↗</Link></div></section>
}
