'use client'
import {useState} from 'react'
import Link from 'next/link'
import {useCart} from '@/components/cart/CartProvider'
import {money} from '@/lib/config/defaults'
import type {SiteSettings} from '@/types'
type Quote={lines:{name:string;quantity:number;lineCents:number;choices:{label:string}[]}[];subtotalCents:number;deliveryFeeCents:number;totalCents:number;deliveryCity?:string|null;deliveryState?:string|null}
type CepResult={postalCode:string;street:string;district:string;city:string;state:string}

export function CheckoutForm({settings,paymentReady}:{settings:SiteSettings;paymentReady:boolean}){
 const {lines,clear}=useCart(),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[cepBusy,setCepBusy]=useState(false),[error,setError]=useState(''),[cepMessage,setCepMessage]=useState(''),[quote,setQuote]=useState<Quote|null>(null),[created,setCreated]=useState<{reference:string;token:string}|null>(null),[key]=useState(()=>crypto.randomUUID())
 const [name,setName]=useState(''),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[method,setMethod]=useState<'pickup'|'delivery'>(settings.pickup_enabled&&settings.address?'pickup':'delivery'),[postalCode,setPostal]=useState(''),[street,setStreet]=useState(''),[number,setNumber]=useState(''),[district,setDistrict]=useState(''),[city,setCity]=useState(''),[state,setState]=useState(''),[complement,setComplement]=useState(''),[notes,setNotes]=useState(''),[paymentMethod,setPaymentMethod]=useState<'online'|'offline'>(settings.offline_payment_enabled?'offline':'online')
 const items=lines.map(l=>({productId:l.productId,quantity:l.quantity,choices:l.choices}))
 const deliveryAddress=method==='delivery'?{street,number,district,city,state,postalCode:postalCode.replace(/\D/g,''),complement}:undefined
 const payload={items,method,postalCode:method==='delivery'?postalCode.replace(/\D/g,''):undefined,address:deliveryAddress}
 const post=async(url:string,body:unknown)=>{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Ocorreu um erro. Tente novamente.');return data}
 async function lookupPostal():Promise<CepResult>{
  const cep=postalCode.replace(/\D/g,'');if(!/^\d{8}$/.test(cep))throw new Error('Informe um CEP válido com 8 dígitos.')
  setCepBusy(true);setCepMessage('Consultando CEP…')
  try{
   const data=await post('/api/address/cep',{cep}) as CepResult
   if(data.street)setStreet(data.street);if(data.district)setDistrict(data.district);setCity(data.city);setState(data.state);setCepMessage(`${data.city} - ${data.state}`);return data
  }finally{setCepBusy(false)}
 }
 async function review(){setError('');setBusy(true);try{
  let nextPayload=payload
  if(method==='delivery'){
   const resolved=await lookupPostal()
   nextPayload={items,method,postalCode:resolved.postalCode,address:{street:street||resolved.street,number,district:district||resolved.district,city:resolved.city,state:resolved.state,postalCode:resolved.postalCode,complement}}
  }
  const q=await post('/api/quote',nextPayload);setQuote(q);setStep(3)
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function submit(){setBusy(true);setError('');try{
  const finalPayload=method==='delivery'?{...payload,address:{...deliveryAddress!,city:quote?.deliveryCity||city,state:quote?.deliveryState||state}}:payload
  const result=await post('/api/orders',{...finalPayload,expectedTotalCents:quote?.totalCents,idempotencyKey:key,name,phone,email:email||undefined,paymentMethod,notes:notes||undefined});setCreated(result);localStorage.setItem(`brutus-order-${result.reference}`,result.token);clear();setStep(4);if(paymentMethod==='online')await beginPayment(result)
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function beginPayment(result=created){if(!result)return;setBusy(true);setError('');try{const pay=await post('/api/payments/start',result);location.assign(pay.url)}catch(e){setError(`${(e as Error).message}. O pedido foi salvo: use o link de acompanhamento abaixo.`);setBusy(false)}}
 const link=created?`/pedido/${created.reference}?token=${created.token}`:''
 return <div className="checkout-layout"><div className="checkout-panel"><div className="checkout-progress">{['Revisão','Identificação','Modalidade','Resumo','Resultado'].map((s,i)=><span key={s} className={i<=step?'current':''}>{String(i+1).padStart(2,'0')} {s}</span>)}</div>
 {lines.length===0&&step===0?<div className="checkout-block"><h2>Seu carrinho está vazio.</h2><p>Escolha um item publicado para começar.</p><Link className="button button-dark" href="/cardapio">Abrir cardápio ↗</Link></div>:null}
 {step===0&&lines.length>0&&<div className="checkout-block"><h2>Confira sua escolha</h2>{lines.map(l=><div className="checkout-row" key={l.key}><span>{l.quantity}× {l.name}<small>{l.choiceLabels.join(' · ')}</small></span><strong>{money(l.quantity*l.unitPriceCents)}</strong></div>)}<label className="input-field">Observações do pedido<textarea value={notes} maxLength={500} onChange={e=>setNotes(e.target.value)} placeholder="Opcional; a equipe confirmará a possibilidade de atender."/></label><button className="button button-dark" onClick={()=>setStep(1)}>Continuar ↗</button></div>}
 {step===1&&<div className="checkout-block"><h2>Como podemos identificar você?</h2><label className="input-field">Nome completo<input required value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label><label className="input-field">Telefone para contato<input required value={phone} onChange={e=>setPhone(e.target.value)} type="tel" autoComplete="tel"/></label><label className="input-field">Email {settings.online_payment_enabled?'(necessário para pagar online)':'(opcional)'}<input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email"/></label><p className="helper">Usaremos esses dados para atender e atualizar seu pedido. O acompanhamento usa um link privado, não uma busca pelo telefone.</p><div className="button-row"><button className="button button-outline" onClick={()=>setStep(0)}>Voltar</button><button className="button button-dark" onClick={()=>{if(name.trim().length<2||!/^\+?[\d\s()\-]{10,24}$/.test(phone)){setError('Informe nome e telefone válidos.');return}setError('');setStep(2)}}>Continuar ↗</button></div></div>}
 {step===2&&<div className="checkout-block"><h2>Como você quer receber?</h2>{!settings.orders_open&&<p className="field-error">A loja está fechada para pedidos.</p>}{settings.pickup_enabled&&settings.address&&<label className="choice large-choice"><input type="radio" checked={method==='pickup'} onChange={()=>setMethod('pickup')}/>Retirar no local <small>{settings.address}</small></label>}{settings.delivery_enabled&&<label className="choice large-choice"><input type="radio" checked={method==='delivery'} onChange={()=>setMethod('delivery')}/>Entrega <small>O CEP identifica a cidade e aplica a taxa fixa configurada pela Brutus.</small></label>}{!settings.pickup_enabled&&!settings.delivery_enabled&&<p>Nenhuma modalidade de pedido foi habilitada pela Brutus.</p>}{method==='delivery'&&settings.delivery_enabled&&<div className="address-grid"><label className="input-field">CEP<input inputMode="numeric" maxLength={9} value={postalCode} onChange={e=>{setPostal(e.target.value);setCity('');setState('');setCepMessage('')}} onBlur={()=>{if(postalCode.replace(/\D/g,'').length===8)void lookupPostal().catch(e=>setError((e as Error).message))}}/>{cepMessage&&<small>{cepMessage}</small>}</label><label className="input-field">Rua<input value={street} onChange={e=>setStreet(e.target.value)}/></label><label className="input-field">Número<input value={number} onChange={e=>setNumber(e.target.value)}/></label><label className="input-field">Bairro<input value={district} onChange={e=>setDistrict(e.target.value)}/></label><label className="input-field">Cidade<input value={city} readOnly placeholder="Preenchida pelo CEP"/></label><label className="input-field">UF<input value={state} readOnly placeholder="UF"/></label><label className="input-field">Complemento (opcional)<input value={complement} onChange={e=>setComplement(e.target.value)}/></label></div>}<div className="button-row"><button className="button button-outline" onClick={()=>setStep(1)}>Voltar</button><button className="button button-dark" disabled={busy||cepBusy||!settings.orders_open||!(settings.pickup_enabled&&settings.address||settings.delivery_enabled)} onClick={review}>{busy||cepBusy?'Verificando…':'Conferir valores ↗'}</button></div></div>}
 {step===3&&quote&&<div className="checkout-block"><h2>Resumo final</h2>{quote.lines.map((l,i)=><div className="checkout-row" key={i}><span>{l.quantity}× {l.name}<small>{l.choices.map(c=>c.label).join(' · ')}</small></span><strong>{money(l.lineCents)}</strong></div>)}<div className="checkout-row"><span>Subtotal</span><strong>{money(quote.subtotalCents)}</strong></div><div className="checkout-row"><span>Taxa de entrega</span><strong>{money(quote.deliveryFeeCents)}</strong></div><div className="checkout-total"><span>Total confirmado</span><strong>{money(quote.totalCents)}</strong></div><p>Modalidade: {method==='pickup'?'Retirada':`Entrega em ${quote.deliveryCity||city} - ${quote.deliveryState||state}`} · {name}</p><div className="payment-choices"><h3>Pagamento</h3>{settings.offline_payment_enabled&&<label className="choice large-choice"><input type="radio" checked={paymentMethod==='offline'} onChange={()=>setPaymentMethod('offline')}/>Pagar no atendimento <small>Permanece pendente até a equipe registrar o recebimento.</small></label>}{settings.online_payment_enabled&&paymentReady&&<label className="choice large-choice"><input type="radio" checked={paymentMethod==='online'} onChange={()=>setPaymentMethod('online')}/>Pagar online <small>Redirecionamento para Mercado Pago; confirmação após verificação oficial.</small></label>}{!settings.offline_payment_enabled&&!(settings.online_payment_enabled&&paymentReady)&&<p>Nenhuma forma de pagamento ativa. A Brutus precisa configurar uma antes de receber pedidos.</p>}</div><div className="button-row"><button className="button button-outline" onClick={()=>setStep(2)}>Alterar dados</button><button className="button button-accent" disabled={busy||!(settings.offline_payment_enabled||settings.online_payment_enabled&&paymentReady)||paymentMethod==='online'&&!email} onClick={submit}>{busy?'Salvando…':'Confirmar pedido ↗'}</button></div><p className="helper">O servidor confere tudo novamente. Se algum valor ou item mudou, você precisará revisar.</p></div>}
 {step===4&&created&&<div className="checkout-block"><span className="kicker">PEDIDO REGISTRADO</span><h2>{created.reference}</h2><p>Seu pedido está registrado. O pagamento está pendente até confirmação verdadeira. Guarde o link privado abaixo.</p><Link className="button button-dark" href={link}>Acompanhar pedido ↗</Link>{paymentMethod==='online'&&<button disabled={busy} className="button button-accent retry-payment" onClick={()=>beginPayment()}>Abrir pagamento ↗</button>}</div>}
 {error&&<p className="checkout-error" role="alert">{error}</p>}
 </div><aside className="checkout-aside"><span className="kicker">SEU CARRINHO</span><h2>{lines.reduce((n,l)=>n+l.quantity,0)} {lines.length===1?'item':'itens'}</h2>{lines.map(l=><div key={l.key} className="checkout-row"><span>{l.quantity}× {l.name}</span><strong>{money(l.unitPriceCents*l.quantity)}</strong></div>)}{!quote&&<div className="checkout-total"><span>Subtotal estimado</span><strong>{money(lines.reduce((n,l)=>n+l.quantity*l.unitPriceCents,0))}</strong></div>}<p>Os valores sempre são recalculados antes de salvar o pedido.</p></aside></div>
}
