import Image from 'next/image'
import Link from 'next/link'
import {ArrowUpRight, ShoppingBag, SlidersHorizontal, MessageCircle, ArrowRight, Instagram} from 'lucide-react'
import {HeroVideo} from '@/components/site/HeroVideo'
import {Gallery} from '@/components/site/Gallery'
import {Reveal} from '@/components/site/Reveal'
import {ProductGrid} from '@/components/menu/ProductGrid'
import {getPublicData} from '@/lib/db/public'
import {whatsappUrl} from '@/lib/whatsapp'
export const dynamic='force-dynamic'
export default async function Home(){
  const data=await getPublicData(),s=data.settings,published=process.env.SITE_APPROVED==='true'
  const featured=data.products.filter(p=>p.featured).slice(0,3)
  const shown=featured.length?featured:data.products.slice(0,3)
  return <Reveal>
    <HeroVideo headline={s.headline}/>
    <div className="brand-ribbon"><span>BRUTUS MATÃO</span><i>✳</i><span>FEITO PARA DAR FOME</span><i>✳</i><span>DO PRIMEIRO OLHAR À ÚLTIMA MORDIDA</span><i>✳</i></div>
    <section id="sobre" className="brand-story"><div className="wrap story-grid" data-reveal>
      <div className="story-copy"><span className="kicker">PRESENÇA. PERSONALIDADE. BRUTUS.</span><h2>Tem fome que<br/>pede <em>mais.</em></h2><p>{s.intro}</p><p className="story-secondary">O encontro marcado, a pausa no dia, a noite que merece um sabor diferente. Cada pedido é um convite para aproveitar.</p><Link href="/cardapio" className="text-link">Conheça o cardápio <ArrowUpRight size={18}/></Link></div>
      {(s.hero_image||!published)?<figure className="story-photo"><Image src={s.hero_image||'/images/burger-concept.png'} alt={s.hero_image?'Brutus Matão':'Hambúrguer com bacon e batatas em fotografia conceitual'} fill sizes="(max-width:800px) 100vw, 50vw"/><figcaption>{s.hero_image?'BRUTUS · MATÃO, SP':'FOTOGRAFIA CONCEITUAL'}</figcaption><div className="story-seal" aria-hidden="true">SEM<br/><em>meia</em><br/>VONTADE.</div></figure>:<div className="brand-type-art" aria-hidden="true">B<span>.</span></div>}
    </div></section>
    <section id="escolhas" className="section-light premium-menu"><div className="wrap" data-reveal><div className="section-head"><div><span className="kicker">ESCOLHAS DA CASA</span><h2>Comece<br/>pelo <em>desejo.</em></h2></div><div className="section-aside"><p>Encontre sua próxima escolha. Explore os lanches da Brutus.</p><Link href="/cardapio" className="text-link">Explorar cardápio <ArrowUpRight size={17}/></Link></div></div>
    {<ProductGrid products={shown} open={s.orders_open||data.preview} emptyText={data.error?'Não foi possível carregar o cardápio. Tente novamente em instantes.':'O cardápio está sendo preparado. Acompanhe as novidades no Instagram.'}/>}</div></section>
    {(!published||s.hero_image)&&<section className="editorial-banner" style={{backgroundImage:`linear-gradient(90deg,#13110ee8,#13110e50),url(${s.hero_image||'/images/burger-concept.png'})`}}><div className="wrap" data-reveal><span className="kicker">A NOITE MERECE.</span><h2>Deixe a rotina.<br/>Siga a <em>vontade.</em></h2><Link href="/cardapio" className="button button-accent">Encontre sua escolha <ArrowUpRight size={18}/></Link>{!s.hero_image&&<small>Imagem conceitual</small>}</div></section>}
    <section id="como-pedir" className="how"><div className="wrap" data-reveal><div className="section-head"><div><span className="kicker">DA ESCOLHA À PRIMEIRA MORDIDA</span><h2>Seu pedido.<br/><em>Do seu jeito.</em></h2></div><p>Escolha com calma. Personalize como gosta. Envie tudo pronto para a Brutus.</p></div><div className="premium-steps">{[{Icon:ShoppingBag,title:'Encontre seu favorito',text:'Explore os itens disponíveis no cardápio.',n:'01'},{Icon:SlidersHorizontal,title:'Coloque seu toque',text:'Escolha as opções de cada lanche e revise o carrinho.',n:'02'},{Icon:MessageCircle,title:'Envie pelo WhatsApp',text:'Informe retirada ou entrega e mande o pedido completo para confirmação.',n:'03'}].map(({Icon,title,text,n})=><article key={n}><div className="step-icon"><Icon size={24}/><span>{n}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <Gallery items={data.gallery}/>
    {data.testimonials.length>0&&<section className="section-light"><div className="wrap" data-reveal><span className="kicker">QUEM JÁ EXPERIMENTOU</span><div className="testimonial-grid">{data.testimonials.map(t=><blockquote key={t.id}><p>“{t.quote}”</p><footer>{t.author} · {t.source}</footer></blockquote>)}</div></div></section>}
    <section className="faq-section"><div className="wrap faq-grid" data-reveal><div><span className="kicker">SEM COMPLICAÇÃO</span><h2>Antes de<br/><em>pedir.</em></h2><a href={whatsappUrl()} target="_blank" rel="noreferrer" className="text-link">Falar com a Brutus <ArrowUpRight size={17}/></a></div><div className="faq-list">{[['Como faço meu pedido?','Entre no cardápio, escolha os itens, revise o carrinho e envie a mensagem pronta para o WhatsApp da Brutus.'],['Posso personalizar meu lanche?','Sim, nos produtos que oferecem personalizações. As opções disponíveis e eventuais valores adicionais aparecem antes de adicionar ao carrinho.'],['Como funcionam entrega e retirada?','Você escolhe retirada ou entrega antes de enviar. A Brutus confirma disponibilidade, endereço, taxa e valor final pelo WhatsApp.'],['Como sei que o pedido foi aceito?','O envio da mensagem não confirma o pedido automaticamente. Aguarde a resposta da Brutus no WhatsApp antes de considerar o pedido confirmado.']].map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></section>
    <section className="contact-section"><div className="wrap contact-card" data-reveal><div><span className="kicker">BRUTUS · MATÃO, SÃO PAULO</span><h2>Sua próxima<br/><em>boa escolha.</em></h2><p>{s.address||'Acompanhe a Brutus, descubra as novidades e deixe a vontade decidir.'}</p><div className="hero-actions"><Link href="/cardapio" className="button button-accent">Ver cardápio <ArrowRight size={18}/></Link><a href={whatsappUrl()} target="_blank" rel="noreferrer" className="contact-social"><MessageCircle size={19}/> WhatsApp <ArrowUpRight size={16}/></a><a href={s.instagram} target="_blank" rel="noreferrer" className="contact-social"><Instagram size={19}/> Instagram <ArrowUpRight size={16}/></a></div></div><div className="contact-monogram" aria-hidden="true">B<span>.</span></div></div></section>
  </Reveal>
}
